# Generated by Django 5.2.5 on 2025-08-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agricultor',
            old_name='data_regsitro',
            new_name='data_registro',
        ),
        migrations.AlterField(
            model_name='agricultor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
